cc_library(
  name = "print",
  visibility = ["//visibility:public"],
  srcs = ["src/format.cpp", "src/print.cpp"],
  hdrs = ["include/printer/format.h", "include/printer/print.h"],
  includes = ["include/printer"],
)
